-- CreateTable
CREATE TABLE "Project" (
    "id" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "description" TEXT,
    "start_date" TIMESTAMP(3),
    "estimated_end_time" TIMESTAMP(3),
    "type" TEXT NOT NULL,
    "is_archived" BOOLEAN NOT NULL DEFAULT false,
    "event_badge_logo" TEXT,
    "race_distance" DOUBLE PRECISION,
    "has_sent_25" BOOLEAN NOT NULL DEFAULT false,
    "has_sent_50" BOOLEAN NOT NULL DEFAULT false,
    "has_sent_75" BOOLEAN NOT NULL DEFAULT false,
    "has_sent_all" BOOLEAN NOT NULL DEFAULT false,
    "race_distance_units" TEXT,
    "race_primary_color" TEXT NOT NULL,
    "race_secondary_color" TEXT NOT NULL,
    "race_event_type" TEXT NOT NULL,
    "event_details_link" TEXT,
    "has_notified" BOOLEAN NOT NULL DEFAULT false,
    "event_sign_up_link" TEXT,
    "time_string" TEXT,
    "config" JSONB,
    "race_banner_image_link" TEXT,
    "project_selfie_filter_image_link" TEXT,
    "cohort_data" JSONB[],
    "project_notification_info" JSONB,
    "open_practice_time" TIMESTAMP(3),
    "next_season_project_id" TEXT,
    "onboarding_image_link" TEXT,
    "onboarding_background_image_link" TEXT,
    "onboarding_background_image_dark_link" TEXT,
    "accepted_activity_types" TEXT[],
    "default_page" TEXT,
    "new_account_link" TEXT,
    "app_welcome_text" TEXT,
    "animation_body" TEXT,
    "animation_function" TEXT,
    "wrapup_image_html" TEXT,

    CONSTRAINT "Project_pkey" PRIMARY KEY ("id")
);
