export enum StorageKey {
  ACTIVITIES = 'activities',
  SYNC_TASKS = 'sync-tasks',
  TRACKED_ACTIVITY = 'tracked-activity',
  ACTIVITY_TYPES = 'activity-types',
  TOKEN = 'token',
  USER = 'user',
  EVENTS = 'events',
  USER_TEAMS = 'user-teams',
  FEATURED_TEAMS = 'featured-teams',
  BADGES = 'badges',
  CHALLENGES = 'challenges',
  PROJECT_BADGES = 'project-badges',
  USER_UNLOCKED_BADGES = 'user-unlocked-badges',
  BADGE_GROUPS = 'badge-groups',
  USER_PETS = 'user-pets',
}
